version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_gofiber
    networks:
      - gofiber-template
    ports:
      - "6380:6379"
    command: ["redis-server", "--requirepass", "admin123"]

networks:
  gofiber-template:
    external: true
