version: '3.8'

services:
  adminer:
    image: adminer
    container_name: adminer_gofiber
    networks:
      - gofiber-template
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres   

networks:
  gofiber-template:
    external: true
